steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubetest:$BRANCH_NAME', '.']
  volumes:
  - name: 'build-volume'
    path: '/workspace/bin'
images: ['gcr.io/$PROJECT_ID/kubetest:$BRANCH_NAME']

